services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./.data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=cmd/worker
    environment:
      ENV: local
      DSN: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ./:/app
    restart: always
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=cmd/api
    ports:
      - 8080:8080
    environment:
      ENV: local
      PORT: 8080
      DSN: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ./:/app
    restart: always
